version: "3.9"

services:
  ml-blue:
    build: .
    image: ml-service:v1.0.0
    environment:
      MODEL_VERSION: "v1.0.0"
      MODEL_PATH: "models/model.pkl"
    ports:
      - "8081:8080"

  ml-green:
    build: .
    image: ml-service:v1.1.0
    environment:
      MODEL_VERSION: "v1.1.0"
      MODEL_PATH: "models/model_1.1.pkl"
    ports:
      - "8082:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ml-blue
      - ml-green

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus